# Generated by Django 6.0.2 on 2026-02-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text="The font's filename (e.g., 'Roboto.ttf')", max_length=100, unique=True)),
                ('types', models.IntegerField(choices=[(0, 'primary'), (1, 'secondary'), (2, 'external')], default=0, help_text='The category of the font.')),
                ('view', models.BigIntegerField(default=0, help_text='Count of views.')),
                ('download', models.BigIntegerField(default=0, help_text='Count of downloads.')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Restricted'), (2, 'Disabled'), (3, 'Missing')], default=0, help_text='The current status of the font.')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'list_font',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemAntonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oem_antonym',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oem_similar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('equivalent', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OEM Spelling Correction',
                'verbose_name_plural': 'OEM Spelling Corrections',
                'db_table': 'oem_spelling',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemThesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oem_thesaurus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OmeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('ipa', models.CharField(blank=True, max_length=255, null=True)),
                ('mlc', models.CharField(blank=True, max_length=255, null=True)),
                ('cate_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ome_word',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_da',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_de',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_el',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_en',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_es',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_fi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdFR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_fr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdHI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_hi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdIW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_iw',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdJA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ko',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_nl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdNO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_no',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_pl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_pt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_ru',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_sv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_th',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_tl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_vi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdZH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, help_text='eg. elske', max_length=250, null=True)),
                ('sense', models.TextField(blank=True, help_text='eg. love; dear', null=True)),
                ('usage', models.TextField(blank=True, help_text='example', null=True)),
                ('status', models.IntegerField(blank=True, help_text='0: default, 1: working, 2: done, 3: not good', null=True)),
            ],
            options={
                'db_table': 'ord_zh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeTerm',
            fields=[
                ('term_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'type_term',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeWord',
            fields=[
                ('word_type', models.IntegerField(db_column='word_type', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('shortname', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'type_word',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='The exact word or phrase searched by the user.', max_length=255)),
                ('lang', models.CharField(db_index=True, help_text="The language ID of the search (e.g., 'en', 'no').", max_length=10)),
                ('count', models.PositiveIntegerField(default=1, help_text='How many times this word has been searched.')),
                ('status', models.IntegerField(default=0, help_text='This field now stores the number of meaning blocks returned.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last time this word was searched.')),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'db_table': 'log_search',
                'ordering': ['-count'],
                'managed': True,
                'unique_together': {('word', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='OemWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('equivalent', models.CharField(blank=True, max_length=250, null=True)),
                ('antonyms', models.ManyToManyField(related_name='related_antonym_entries', through='core.OemAntonym', to='core.oemword')),
                ('similar', models.ManyToManyField(related_name='related_similar_entries', through='core.OemSimilar', to='core.oemword')),
                ('thesaurus', models.ManyToManyField(related_name='related_thesaurus_entries', through='core.OemThesaurus', to='core.oemword')),
                ('derived', models.ForeignKey(db_column='derived', on_delete=django.db.models.deletion.CASCADE, to='core.typeword')),
            ],
            options={
                'db_table': 'oem_word',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oemthesaurus',
            name='from_word',
            field=models.ForeignKey(db_column='wrid', on_delete=django.db.models.deletion.CASCADE, related_name='from_thesaurus', to='core.oemword'),
        ),
        migrations.AddField(
            model_name='oemthesaurus',
            name='to_word',
            field=models.ForeignKey(db_column='wlid', on_delete=django.db.models.deletion.CASCADE, related_name='to_thesaurus', to='core.oemword'),
        ),
        migrations.AddField(
            model_name='oemsimilar',
            name='from_word',
            field=models.ForeignKey(db_column='wrid', on_delete=django.db.models.deletion.CASCADE, related_name='from_similar', to='core.oemword'),
        ),
        migrations.AddField(
            model_name='oemsimilar',
            name='to_word',
            field=models.ForeignKey(db_column='wlid', on_delete=django.db.models.deletion.CASCADE, related_name='to_similar', to='core.oemword'),
        ),
        migrations.AddField(
            model_name='oemantonym',
            name='from_word',
            field=models.ForeignKey(db_column='wrid', on_delete=django.db.models.deletion.CASCADE, related_name='from_antonym', to='core.oemword'),
        ),
        migrations.AddField(
            model_name='oemantonym',
            name='to_word',
            field=models.ForeignKey(db_column='wlid', on_delete=django.db.models.deletion.CASCADE, related_name='to_antonym', to='core.oemword'),
        ),
        migrations.CreateModel(
            name='OmeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymology', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('variant', models.TextField(blank=True, null=True)),
                ('wrid', models.ForeignKey(db_column='wrid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.omeword')),
            ],
            options={
                'db_table': 'ome_reference',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeDerived',
            fields=[
                ('derived_type', models.AutoField(primary_key=True, serialize=False)),
                ('derivation', models.CharField(blank=True, max_length=20, null=True)),
                ('word_type', models.ForeignKey(db_column='word_type', on_delete=django.db.models.deletion.CASCADE, to='core.typeword')),
            ],
            options={
                'db_table': 'type_derived',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OmeThesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlid', models.ForeignKey(db_column='wlid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='omethesaurus_wlid_set', to='core.omeword')),
                ('wrid', models.ForeignKey(db_column='wrid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.omeword')),
                ('cate', models.ForeignKey(blank=True, db_column='cate', db_comment='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.typeword')),
            ],
            options={
                'db_table': 'ome_thesaurus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OmeSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.IntegerField(db_comment='word reference id')),
                ('cate', models.IntegerField(blank=True, db_comment='category', null=True)),
                ('sense', models.TextField(blank=True, db_comment='Definition', null=True)),
                ('exam', models.TextField(blank=True, db_comment='Example', null=True)),
                ('wseq', models.IntegerField(default=0)),
                ('wrkd', models.IntegerField(blank=True, db_comment='Source id', null=True)),
                ('usg', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('dated', models.DateTimeField()),
                ('wrid', models.ForeignKey(db_column='wrid', db_comment='word id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.omeword')),
                ('trid', models.ForeignKey(blank=True, db_column='trid', db_comment='0:unknown, 1:word, 2:phrase, 3:sentence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.typeterm')),
                ('wrte', models.ForeignKey(db_column='wrte', db_comment='word type of POS', on_delete=django.db.models.deletion.DO_NOTHING, to='core.typeword')),
            ],
            options={
                'db_table': 'ome_sense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('sense', models.TextField(blank=True, null=True)),
                ('exam', models.TextField(blank=True, null=True)),
                ('wseq', models.IntegerField(default=0)),
                ('wrkd', models.IntegerField(default=0, help_text='Corresponds to type_sense.id in the original schema')),
                ('dated', models.DateTimeField(auto_now_add=True)),
                ('wrid', models.ForeignKey(blank=True, db_column='wrid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.oemword')),
                ('wrte', models.ForeignKey(blank=True, db_column='wrte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typeword')),
            ],
            options={
                'db_table': 'oem_sense',
                'ordering': ['wseq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OemDerived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrig', models.IntegerField(default=0, help_text='Irregular flag')),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_word_mappings', to='core.oemword')),
                ('derived_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_word_mappings', to='core.oemword')),
                ('dete', models.ForeignKey(blank=True, db_column='dete', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typederived')),
                ('wrte', models.ForeignKey(db_column='wrte', default=0, on_delete=django.db.models.deletion.CASCADE, to='core.typeword')),
            ],
            options={
                'db_table': 'oem_derived',
                'managed': True,
            },
        ),
    ]
