# Generated by Django 5.2.5 on 2025-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text="The font's filename (e.g., 'Roboto.ttf')", max_length=50, unique=True)),
                ('types', models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'External')], default=1, help_text='0: primary, 1: secondary, 2: external')),
                ('view', models.BigIntegerField(default=0, help_text='View count')),
                ('download', models.BigIntegerField(default=0, help_text='Download count')),
                ('restricted', models.BooleanField(default=False, help_text='If true, download is disabled')),
                ('dated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last interaction')),
            ],
            options={
                'db_table': 'log_fonts',
                'ordering': ['-view', '-download'],
                'indexes': [models.Index(fields=['file'], name='log_fonts_file_a74a3b_idx')],
            },
        ),
    ]
