# Generated by Django 5.2.6 on 2025-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fonts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonts',
            name='dated',
        ),
        migrations.RemoveField(
            model_name='fonts',
            name='restricted',
        ),
        migrations.AddField(
            model_name='fonts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Disabled'), (2, 'Missing')], default=0, help_text='The current status of the font.'),
        ),
    ]
