# Generated by Django 5.2.6 on 2025-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_fonts_dated_remove_fonts_restricted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonts',
            name='file',
            field=models.CharField(help_text="The font's filename (e.g., 'Roboto.ttf')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fonts',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
