# Generated by Django 5.2.6 on 2025-09-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fonts_file_alter_fonts_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonts',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Restricted'), (2, 'Disabled'), (3, 'Missing')], default=0, help_text='The current status of the font.'),
        ),
    ]
