# Generated by Django 5.2.6 on 2025-09-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fonts_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonts',
            new_name='ListFont',
        ),
        migrations.AlterModelTable(
            name='listfont',
            table='list_font',
        ),
    ]
