"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
# from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
    # ==========================================
    # OPTION 1: The Redirect Method (Easiest)
    # ==========================================
    # This tells the browser: "The file is actually over here in /static/."
    # Browsers handle this 301/302 redirect perfectly for favicons.
    # path(
    #     'favicon.png', 
    #     RedirectView.as_view(url=f'{settings.STATIC_URL}favicon.png', permanent=True)
    # ),

    # ==========================================
    # OPTION 2: The Direct Serve Method (Strict 200 OK)
    # ==========================================
    # Some tools (like Googlebot looking for robots.txt) strictly prefer a 
    # 200 OK response at the root, rather than a redirect.
    # This serves the file directly from your static folder as if it were at the root.
    path(
        'favicon.png', 
        serve, 
        {
            'document_root': settings.STATICFILES_DIRS[0],
            'path': 'favicon.png'
        }
    ),
    
    # You can also do this for files generated by Webpack if you know their exact name:
    # path('manifest.json', serve, {'document_root': settings.STATICFILES_DIRS[0], 'path': 'manifest.json'}),
]

# Add these lines to change the admin titles
admin.site.site_header = "MyOrdbok"
admin.site.site_title = "A comprehensive online English to or from Myanmar dictionary"
admin.site.index_title = "Admin"